version: '3.8'

services:
  frontend:
    container_name: personality-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5040:80"
    depends_on:
      - backend
      

  backend:
    container_name: personality-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5050:5050"